package org.study.drools;
import org.study.drools.Messages;
dialect  "mvel"

rule "First Rule"

    when
        order:Order(sumprice>30,sumprice<=50);
    then
        order.setDiscountPercent(98);

end

rule "Second Rule"
    when
        order:Order(sumprice>50,sumprice<=100);
    then
        order.setDiscountPercent(95);



end

//rule "third Rule"
rule "using a static function"
    when
        order:Order(sumprice>100);
    then
        order.setDiscountPercent(90);
        hello(Messages.ONE);
end



function String hello(String out){
    return out;
}